# **Árvore de decisão para análise de crédito**

In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# **importando os dados da análise**

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/credito_correto.csv')

# **Os dados contém 2000 registros para análise e 4 colunas (rendimento,idade,dívida e inadimplencia)**

In [ ]:
data

        rendimento      idade       dívida  inadimplencia
0     66155.925095  59.017015  8106.532131              0
1     34415.153966  48.117153  6564.745018              0
2     57317.170063  63.108049  8020.953296              0
3     42709.534201  45.751972  6103.642260              0
4     66952.688845  18.584336  8770.099235              1
...            ...        ...          ...            ...
1995  59221.044874  48.518179  1926.729397              0
1996  69516.127573  23.162104  3503.176156              0
1997  44311.449262  28.017167  5522.786693              1
1998  43756.056605  63.971796  1622.722598              0
1999  69436.579552  56.152617  7378.833599              0

[2000 rows x 4 columns]

# **rendimento, idade e dívida serão usados para a máquina classificar como possiveis inadimplentes**

In [ ]:
x = data[['idade','dívida','rendimento']]
y = data['inadimplencia']

# **usaremos 500 registros para treinar nossa maquina e 1500 registros para testar a acertividade da máquina**

In [ ]:
x_treino = x[:500].values
y_treino = y[:500].values
x_teste = x[500:].values
y_teste = y[500:].values

In [ ]:
modelo = DecisionTreeClassifier() 
modelo.fit(x_treino, y_treino)
previsoes = modelo.predict(x_teste)

acuracia = accuracy_score(y_teste, previsoes) * 100
print(f'a acertividade foi de {acuracia}')

a acertividade foi de 96.2

# **nesta análise obtivemos uma acertividade de 96,2% com nossa Árvore de decisão** (por:Lucas Mareglia)